### ISSUE TITLE
Something about CA(Cross attention)

### ISSUE THREAD

**Issue by freeman-1995** [salesforce/BLIP#8]
CA is used to inject visual information when doing text encoding, can I use CA to inject text information when image encoding in the same way?
what's the difference between this two designs, which one is best?

**Comment by LiJunnan1992** [comment]
great question. You can use CA to inject text information into image encoding. The reasons that BLIP injects visual information into text are as follows:

1. It is a natural design for the image captioning task with a text decoder. Since BLIP share parameters between the text encoder & decoder, the text encoder also follow the same design.

2. It is more computation efficient, because the sequence length of the text (<40) is usually much smaller than the sequence length of the image (>197).

**Comment by freeman-1995** [comment]
> great question. You can use CA to inject text information into image encoding. The reasons that BLIP injects visual information into text are as follows:
> 
> 1. It is a natural design for the image captioning task with a text decoder. Since BLIP share parameters between the text encoder & decoder, the text encoder also follow the same design.
> 2. It is more computation efficient, because the sequence length of the text (<40) is usually much smaller than the sequence length of the image (>197).

thanks  a lot
